### ISSUE TITLE
build broken, code maturity status unclear

### ISSUE THREAD

**Issue by speters** [thelsing/vcontrold#1]
Hi thelsing (Thomas?),

nice to see your ongoing work on _vcontrold_.
Unfortunately, it broke the build of _vcontrold_ partially and _vclient_ completely.

The _autotools_ files could be updated to reflect the changed filenames and dependencies:
```diff
diff --git a/vcontrold/Makefile.am b/vcontrold/Makefile.am
index f71c41b..69faacf 100644
--- a/vcontrold/Makefile.am
+++ b/vcontrold/Makefile.am
@@ -6,5 +6,5 @@ AM_LDFLAGS =
 # the previous manual Makefile
 sbin_PROGRAMS = vcontrold
 bin_PROGRAMS = vclient vsim
-vcontrold_SOURCES = vcontrold.c parser.c framer.c io.c common.c socket.c xmlconfig.c arithmetic.c unit.c parser.h framer.h io.h common.h socket.h xmlconfig.h arithmetic.h unit.h
-vclient_SOURCES = vclient.c client.c client.h prompt.h common.c common.h socket.c socket.h io.c io.h
+vcontrold_SOURCES = vcontrold.cpp parser.cpp framer.cpp io.cpp common.cpp socket.cpp xmlconfig.cpp conversion.cpp parser.h framer.h io.h common.h socket.h xmlconfig.h conversion.h
+vclient_SOURCES = vclient.c client.c client.h prompt.h common.cpp common.h socket.cpp socket.h io.cpp io.h
diff --git a/vcontrold/configure.ac b/vcontrold/configure.ac
index 2f34da2..47ef0b5 100644
--- a/vcontrold/configure.ac
+++ b/vcontrold/configure.ac
@@ -6,11 +6,12 @@ AC_INIT(vcontrol, 1.0, mschroether@gmx.de)
 
 AM_INIT_AUTOMAKE(no-dependencies)
 
-AC_CONFIG_SRCDIR([vcontrold.c])
+AC_CONFIG_SRCDIR([vcontrold.cpp])
 #AC_CONFIG_HEADER([config.h])
 
 # Checks for programs.
 AC_PROG_CC
+AC_PROG_CXX
 
 # xml2
 AC_ARG_WITH(xml2-include-dir,
@@ -55,8 +56,8 @@ if test "x$XML2_LIBS" = "x"; then
        AC_MSG_ERROR([XML2 libraries not found.  Use --with-xml2-lib-dir=<path>])
 fi
 # don't forget to add xml2 to the list of libraries
-LIBS="-lxml2 -lpthread $LIBS"
-
+LIBS="-lxml2 -lpthread -lyaml-cpp $LIBS"
+CXXFLAGS="-O2 -std=c++11"
 # Checks for header files.
 AC_HEADER_STDC
 AC_CHECK_HEADERS([arpa/inet.h fcntl.h netdb.h stdint.h stdlib.h string.h sys/ioctl.h sys/socket.h sys/time.h syslog.h termios.h unistd.h sys/types.h sys/ipc.h sys/sem.h])
```
With this, at least a `sh auto-build.sh && ./configure && make vcontrold` is possible.

Currently, I'm really unsure about the maturity/status of your version.
The changelog showed some comments about some changes to the XML structure. Maybe you could clarify this, and supply an example of known-good XML configuration files.

Viele Grüße,
Sönke Petes

**Comment by thelsing** [comment]
Hi Sönke,

I develop using Visual Studio 2015 with "Visual C++ for Linux Development" so I don't use the Makefile. But  I wanted to fix it in the future. I applied your path. Thanks.

This fork was started because the old vcontrold was to slow to fetch all my datapoints every minute. 
Now I use a plugin (https://github.com/thelsing/viessmann) for smarthomeNG (https://github.com/smarthomeNG/smarthome/wiki) to get the data. It takes 4-5s on a raspberry pi now.

I removed some stuff I don't need:
-vclient
-units
-multi-device support

In the future I plan to add bulk reading from the heater.

Here are my current xml files:

[protocol.xml.txt](https://github.com/thelsing/vcontrold/files/595663/protocol.xml.txt)
[vcontrold.xml.txt](https://github.com/thelsing/vcontrold/files/595664/vcontrold.xml.txt)
[vito.xml.txt](https://github.com/thelsing/vcontrold/files/595665/vito.xml.txt)

vito.xml was generated with viessmannADR (https://github.com/thelsing/viessmannADR) from the
vitosoft demo (https://update-vitosoft.viessmann.com/CurrentVersion/Vitosoft300WithoutDocs.iso)

I plan to move to commands in vito.xml to datapoints and generate the set and get commands at runtime.

Feel free to ask any further questions ;)

Regards,
Thomas

**Comment by thelsing** [comment]
A quick note on code maturity: works for me ;).

**Comment by speters** [comment]
Danke für die tollen Hinweise. Ich hatte bei deinem viessmannADR Tool bereits gedacht, dass du Zugriff auf "offizielle" Datenpunktdateien hast, wusste aber nicht, dass Viessmann da sogar eine Demoversion anbietet.

Ich habe die XML Dateien direkt aus der ISO extrahiert, weil ich kein Windows habe (und mir das auch ziemlich nach Softwaremonster aussah). Script dazu s.u. (i.w. 7zip).

Thx for the great hints. I already assumed you were using "official" data point description files on your viessmannADR tool, but didn't know that there's a demo version offered by Viessmann.

I pulled the XML files directly from the ISO, because I don't run Windows (and the whole stuff looked like bloatware). Extraction script below (mainly 7zip).

[getvitoxml.sh](https://gist.github.com/speters/57896313e35f4593f6efa85f793690ec)

**Comment by thelsing** [comment]
Wenn du nur die XML-Dateien extrahierst, hast du aber alle Datenpunkte zu allen Geräten. Wenn du die Software installierst einmal mit deinem Heizgerät nutzt, und dann meine Tool ausführst, bekommst du nur die Datenpunkte die dein Gerät auch unterstützt. (Gruppiert nach diversen Gruppen aus dem Viessmann-Tool).
